### ISSUE TITLE
Sensors stop working after a few hours

### ISSUE THREAD

**Issue by anderl78** [TheRealKillaruna/nano_pk#15]
Hello!

At first: Thank you for this Integration!

My setup is done as described (SD-Card, full dataset, nano_pk 25, Firmware 14.0HAR.o2). It is working as expected, but after a few hours (can't say exactly how long) it stops. The sensors don't show new values any longer. 

I already tried to get them online again with "Home Assistant Core Integration: update entity" manually, but without success... only a restart of Home Assistant helps to get them back online. This seems not to be a problem of HA itself, because all other sensors are working as expected.

After that I thought about a communication problem of the boiler. I checked if he is still active in my home network - my fritzbox shows me as active component only the internet-gatway from hargassner, the boiler is not listed in the "active sektion" - but don't really trust this, sometimes it seems to be inaccurate to me...

Btw, the Hargassner App shows all sensor variables without any problem all the time... the boiler itself is working too (burning and so on....)

I'm currently trying to get a ping every 10 minutes, perhaps this helps me out... I will let you know.

Is there somebody else with this behavour? Perhaps with a solution? Or what can I do to help drilling this down?

**Comment by anderl78** [comment]
Hmm, sadly there seems to be a problem with this Integration. My idea was without success... 
There is an other issue open, same problem there. @LucHeart fixed it in his fork. Here is the link: https://github.com/TheRealKillaruna/nano_pk/issues/5#issuecomment-1048672902

Would be great if this could be thrown together....

**Comment by LucHeart** [comment]
I could try to merge in the latest changes from here, and make a PR after :D

**Comment by skrue** [comment]
Hi @LucHeart and @TheRealKillaruna, I'd very much appreciate it if any of you could integrate the fixes with the most recent version in this repo. I am also experiencing the issue where the integration would lock up and stop working whenever the Hargassner gateway becomes unreachable. Apart from that, the integration is doing a great job and I appreciate the work that went into it!

**Comment by TheRealKillaruna** [comment]
Hi all, I have completely reworked the network code and message parsing of the integration. It would be great if you could try the latest version and report back if that resolves the issues you had. Thanks!

**Comment by TheRealKillaruna** [comment]
@skrue don't worry about these errors for now, I get the same in my logs and they can be fixed for sure. What I'm interested in is if the network connection is stable now, i.e. if the sensors keep working with this new version or if they stop after some time (as in the previous version).

**Comment by skrue** [comment]
Alright, I have now done some testing. My issue was that the integration stopped working when the network connection to the gateway went down. So I disconnected the gateway on purpose and saw the following errors:
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1182
First occurred: 21:48:30 (1 occurrences)
Last logged: 21:48:30

Update of sensor.nano_pk_connection is taking over 10 seconds
```
followed by
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:858
Integration: Sensor (documentation, issues)
First occurred: 11. Januar 2024 um 19:25:44 (8 occurrences)
Last logged: 21:48:55

Updating nano_pk sensor took longer than the scheduled update interval 0:00:05
```
and
```
Logger: custom_components.nano_pk.sensor
Source: custom_components/nano_pk/sensor.py:196
Integration: Hargassner Nano-PK (documentation)
First occurred: 12. Januar 2024 um 09:56:19 (18 occurrences)
Last logged: 21:50:10

HargassnerBridge.async_update(): Telnet connection error (TimeoutError())
HargassnerBridge.async_update(): Error opening connection
```

After plugging the gateway's ethernet cable back in, the integration re-established the connection and resumed normal operation. So as far as I am concerned, the main issue of the integration locking up is now solved.
However it would be nice to have the errors on startup (from my previous comment) ironed out.

**Comment by TheRealKillaruna** [comment]
@skrue, thanks for the confirmation! I have fixed the startup errors now as well and am closing this issue.

**Comment by skrue** [comment]
I have tested the updated version now and can confirm that the `Error while setting up nano_pk platform for sensor` error that I was seeing on startup is gone.

I am still seeing the other two (twice) during startup, but that's probably expected because it takes a few seconds to establish the Telnet connection to the Hargassner gateway, right?
```
2024-01-14 13:50:42.946 WARNING (MainThread) [custom_components.nano_pk.sensor] HargassnerStateSensor.update(): Invalid state.
2024-01-14 13:50:42.996 WARNING (MainThread) [custom_components.nano_pk.sensor] HargassnerEnergySensor.update(): Invalid value.
2024-01-14 13:50:47.598 WARNING (MainThread) [custom_components.nano_pk.sensor] HargassnerStateSensor.update(): Invalid state.
2024-01-14 13:50:47.745 WARNING (MainThread) [custom_components.nano_pk.sensor] HargassnerEnergySensor.update(): Invalid value.
```

**Comment by TheRealKillaruna** [comment]
Exactly, this happens when the connection is still being set up and the state cannot be retrieved. If you see this message all the time, then you have an issue, but a couple of times is normal. This is why I also changed the log category from error to warning.

**Comment by michi3120** [comment]
Hi, 
unfortunatley this didn´t solve my issue. 
The behavior has changed now. Bevor your updated version the states just didn´t change any more after a while. Now it says entity is not available. 

In the HA error log i get these errors: 
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.nano_pk.sensor
Source: custom_components/nano_pk/sensor.py:143
Integration: Hargassner Nano-PK (documentation)
First occurred: 15. Januar 2024, 19:39:33 (28156 occurrences)
Last logged: 22:28:57

HargassnerEnergySensor.update(): Invalid value.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.nano_pk.sensor
Source: custom_components/nano_pk/sensor.py:196
Integration: Hargassner Nano-PK (documentation)
First occurred: 15. Januar 2024, 19:39:33 (28156 occurrences)
Last logged: 22:28:56

HargassnerBridge.getUnit(): Parameter key Verbrauchszähler not known. HargassnerBridge.getUnit(): Parameter key Verbrauchszähler not known.
HargassnerBridge.getValue(): Parameter key Verbrauchszähler not known.
HargassnerBridge.getValue(): Parameter key Verbrauchszähler not known. HargassnerBridge.async_update(): Telnet connection error (TimeoutError())
HargassnerBridge.getValue(): Parameter key Verbrauchszähler not known. HargassnerBridge.async_update(): Telnet connection error (ConnectionResetError(104, 'Connection reset by peer')) HargassnerBridge.async_update(): Error opening connection
HargassnerBridge.getValue(): Parameter key Verbrauchszähler not known. HargassnerBridge.async_update(): Error opening connection


My HA integration is running in a Docker container on my NAS. The NAS is switched off at night an starts in the mornig. I think that´s when the error occurs.
